#Autor Eduardo Moreno
swagger: '2.0'
host: reaktor
basePath: /reaktor
schemes:
  - "https"
info:
  title: Filtro por pc, profesor y aula file 1
  version: 1.0.0
  contact:
     name: "Eduardo Moreno"
     email: "emoralg196@g.educaand.es"

# TODO Los paths son /visual/PC/{numeroPlacaBase}, /visual/aula/{numero_de_aula} y /visual/profesor/{id}




paths:
  /visual/PC/{numeroPlacaBase}:
    get:
      summary: Obtener información de un portátil por número de placa base
      parameters:
        - name: numeroPlacaBase
          in: path
          type: integer
          format: int32
          required: true
          description: Número de la placa base del portátil
      responses:
        200:
          description: Éxito, se encontró el portátil
          schema:
            $ref: "#/definitions/Portatil"
        404:
          description: No se encontró el portátil

  /visual/aula/{numero_de_aula}:
    get:
      summary: Obtener información de un aula por número de aula
      parameters:
        - name: numero_de_aula
          in: path
          type: integer
          required: true
          description: Número de aula
      responses:
        200:
          description: Éxito, se encontró el aula
          schema:
            $ref: "#/definitions/Aula"
        404:
          description: No se encontró el aula

  /visual/profesor/{id}:
    get:
      summary: Obtener información de un profesor por ID
      parameters:
        - name: id
          in: path
          type: integer
          format: int64
          required: true
          description: Identificador del profesor
      responses:
        200:
          description: Éxito, se encontró el profesor
          schema:
            $ref: "#/definitions/Profesor"
        404:
          description: No se encontró el profesor

definitions:
  Portatil:
      type: object
      properties: 
        numeroJuntaAndalucia:
          type: integer
          format: int32
          description: "Numero de la junta de andalucia"
        numeroPlacaBase:
          type: integer
          format: int32
          description: "Numero de la placa base del portatil"
        numeroPortatil:
          type: integer
          format: int32
          description: "Pegatina que posee el portatil"
        status:
          type: boolean
          description: true if the pc is on, false if the pc is off
          default: true
        reboot: 
          type: boolean
          default: false
          description: set the pc of if this value is true
        locked:
          type: boolean
          description: lock the pc if this value is true
        
        Hardware:
          $ref: "#/definitions/Hardware"
  Hardware:
    type: object
    properties: 
        CPU:
          $ref: '#/definitions/CPU'
        RAM:
          $ref: '#/definitions/RAM'
        HardDisk:
          $ref: '#/definitions/HardDisk'
  CPU:
    properties:
      number:
        type: integer
        format: int32
      brand:
        type: string
  RAM:
    properties: 
      size: 
        type: integer
        format: int32
      brand: 
        type: string
  HardDisk:
    properties: 
      size: 
        type: integer
        format: int32
      currentSize: 
        type: integer
        format: int32
      brand: 
        type: string
  App:
    type: object
    properties: 
      nameApp:
        type: string
      isMalware:
        type: boolean
        default: false
      uninstall:
        type: boolean
        default: false
      execute:
        type: boolean
        default: false
  Profesor:
    type: object
    properties:
      id:
        type: integer
        format: int64
      nombre:
        type: string
  Aula:
    type: object
    properties:
      numero_de_aula:
        type: integer
        description: Número de aula
      id_profesor:
        type: integer
        description: Identificador del profesor asignado
