#Autor Pablo Ruiz Canovas
#TODO Realizar getters que pidan ultimo reinicio, ultimo codigo ejecutado, ultimo enlace
#TODO ultima instalacion, ultima desisntalacion
swagger: '2.0'
host: reaktor
basePath: /reaktor
schemes:
  - https
info:
  title: Ultima monitorizacion file 8
  description: Send WiFi connection to profesores, aulas, carritos
  version: 1.0.0
  contact:
    name: Pablo Ruiz Canovas
    email: pruican1312@g.educaand.es
#TODO Usar los paths /visual/getLastReboot, /visual/getLastExe, /visual/getLastLink, /visual/getLastInstall, /visual/getLastUninstall
paths:
  /visual/getLastReboot/{numeroPortatil}:
    get:
      operationId: getLastReboot
      description: Se obtiene el ultimo reinicio de un portatil usando su pegatina
      parameters:
        - name: numeroPortatil
          type: integer
          format: int32
          in: path
          required: true
      responses:
        200:
          description: Ultimo reinicio obtenido satisfactoriamente
          schema:
            $ref: "#/definitions/UltimaAccion"
        404:
          description: Error al introducir parametros
          schema:
            $ref: "#/definitions/VisualException"
        500:
          description: Error interno de servidor
          schema:
            $ref: "#/definitions/VisualException"
  /visual/getLastExe/{numeroPortatil}:
    get:
      operationId: getLastReboot
      description: Se obtiene el ultimo programa ejecutado de un portatil usando su pegatina
      parameters:
        - name: numeroPortatil
          type: integer
          format: int32
          in: path
          required: true
      responses:
        200:
          description: Ultimo reinicio obtenido satisfactoriamente
          schema:
            $ref: "#/definitions/UltimaAccion"
        404:
          description: Error al introducir parametros
          schema:
            $ref: "#/definitions/VisualException"
        500:
          description: Error interno de servidor
          schema:
            $ref: "#/definitions/VisualException"
  /visual/getLastLink/{numeroPortatil}:
    get:
      operationId: getLastReboot
      description: Se obtiene el ultimo enlace de un portatil usando su pegatina
      parameters:
        - name: numeroPortatil
          type: integer
          format: int32
          in: path
          required: true
      responses:
        200:
          description: Ultimo reinicio obtenido satisfactoriamente
          schema:
            $ref: "#/definitions/UltimaAccion"
        404:
          description: Error al introducir parametros
          schema:
            $ref: "#/definitions/VisualException"
        500:
          description: Error interno de servidor
          schema:
            $ref: "#/definitions/VisualException"
  /visual/getLastInstall/{numeroPortatil}:
    get:
      operationId: getLastReboot
      description: Se obtiene la ultima instalacion de un portatil usando su pegatina
      parameters:
        - name: numeroPortatil
          type: integer
          format: int32
          in: path
          required: true
      responses:
        200:
          description: Ultimo reinicio obtenido satisfactoriamente
          schema:
            $ref: "#/definitions/UltimaAccion"
        404:
          description: Error al introducir parametros
          schema:
            $ref: "#/definitions/VisualException"
        500:
          description: Error interno de servidor
          schema:
            $ref: "#/definitions/VisualException"
  /visual/getLastUninstall/{numeroPortatil}:
    get:
      operationId: getLastReboot
      description: Se obtiene la ultima desinstalacion de un portatil usando su pegatina
      parameters:
        - name: numeroPortatil
          type: integer
          format: int32
          in: path
          required: true
      responses:
        200:
          description: Ultimo reinicio obtenido satisfactoriamente
          schema:
            $ref: "#/definitions/UltimaAccion"
        404:
          description: Error al introducir parametros
          schema:
            $ref: "#/definitions/VisualException"
        500:
          description: Error interno de servidor
          schema:
            $ref: "#/definitions/VisualException"
#OBJETOS
definitions:
  Portatil:
    type: object
    properties: 
      numeroJuntaAndalucia:
        type: integer
        format: int32
        description: "Numero de la junta de andalucia"
      numeroPlacaBase:
        type: integer
        format: int32
        description: "Numero de la placa base del portatil"
      numeroPortatil:
        type: integer
        format: int32
        description: "Pegatina que posee el portatil"
      status:
        type: boolean
        description: true if the pc is on, false if the pc is off
        default: true
      reboot: 
        type: boolean
        default: false
        description: set the pc of if this value is true
      locked:
        type: boolean
        description: lock the pc if this value is true
      appsInstalled:
        type: array
        description: An array of apps that the pc have installed
        $ref: "#definitions/App"
      Hardware:
        $ref: '#definitions/Hardware'
  Hardware:
    type: object
    properties: 
        CPU:
          $ref: '#/definitions/CPU'
        RAM:
          $ref: '#/definitions/RAM'
        HardDisk:
          $ref: '#/definitions/HardDisk'
  CPU:
    properties:
      number:
        type: integer
        format: int32
      brand:
        type: string
  RAM:
    properties: 
      size: 
        type: integer
        format: int32
      brand: 
        type: string
  HardDisk:
    properties: 
      size: 
        type: integer
        format: int32
      currentSize: 
        type: integer
        format: int32
      brand: 
        type: string
  App:
    type: object
    properties: 
      nameApp:
        type: string
      isMalware:
        type: boolean
        default: false
      uninstall:
        type: boolean
        default: false
      execute:
        type: boolean
        default: false
  UltimaAccion:
    type: object
    properties: 
      ultimoReinicio:
        type: string
        description: Ultimo reinicio realizado en tipo date almacenado en string
      ultimaEjecucion:
        type: string
        description: Ultima ejecucion realizada en tipo date almacenado en string
      ultimoBloqueo:
        type: string
        description: Ultimo bloqueo realizado en tipo date almacenado en string
      ultimoEnlace:
        type: string
        description: Ultimo enlace abierto realizado en tipo date almacenado en string
      ultimaInstalacion:
        type: string
        description: Ultima app instalada abierta realizado en tipo date almacenado en string
      ultimaDesinstalacion:
        type: string
        description: Ultima app desinstalada abierta realizado en tipo date almacenado en string
  VisualException:
    type: object
    properties: 
      errorCode:
        type: integer
        format: int32
      description:
        type: string
      errorSeverity:
        type: string