#Autores Pablo Ruiz, Adrian Verdejo, Eduardo Moreno
swagger: '2.0'
host: reaktor
basePath: /reaktor
schemes:
  - https
info: 
  version: 1.0.0
  title: Reaktor Swagger Documentation
  description: Reaktor rss 
  contact:
    name: Pablo Ruiz Canovas, Eduardo Moreno, Adrian Verdejo



