swagger: '2.0'
host: reaktor
basePath: /reaktor
schemes:
  - https
info: 
  version: 1.0.0
  title: Reaktor Swagger Documentation
  description: Reaktor rss 
  contact:
    name: Pablo Ruiz Canovas, Eduardo Moreno, Adrian Verdejo
produces:
  - application/json
paths: 
  /visual/PC/{numeroPlacaBase}:
    get:
      operationId: getPCByNumSerie
      description: Se obtiene un pc por el numero de la placa base
      parameters:
        - name: numeroPlacaBase
          description: Numero de la placa base de un pc
          type: integer
          format: int64
          in: path
          required: true
      responses:
        200:
          description: Pc obtenido mostrando los datos
          schema:
            $ref: "#/definitions/Portatil"
        404:
          description: Datos mal introducidos
          schema:
            $ref: "#/definitions/VisualException"
        500:
          description: Error interno de servidor
          schema:
            $ref: "#/definitions/VisualException"
  /visual/PC/aula/{numero_de_aula}:
    get:
      operationId: getPCByAula
      description: Se obtiene un ordenador o varios a traves de un aula
      parameters:
        - name: numero_de_aula
          description: Numero de aula donde se encuentra los portatiles
          type: integer
          format: int32
          in: path
          required: true
      responses:
        200:
          description: Ordenadores obtenidos
          schema:
            type: array
            items: 
              $ref: "#/definitions/Portatil"
        404:
          description: Error al introducir el aula
          schema:
            $ref: "#/definitions/VisualException"
        500:
          description: Error interno de servidor
          schema:
            $ref: "#/definitions/VisualException"
  /visual/PC/profesor/{nombre}:
    get:
      operationId: getPCByProfesor
      description: Se obtiene un ordenador o varios a traves de un aula
      parameters:
        - name: nombre
          description: Nombre del profesor que esta controlando los portatiles
          type: string
          in: path
          required: true
      responses:
        200:
          description: Ordenadores obtenidos
          schema:
            type: array
            items: 
              $ref: "#/definitions/Portatil"
        404:
          description: Error al introducir el nombre del profesor
          schema:
            $ref: "#/definitions/VisualException"
        500:
          description: Error interno de servidor
  
  /visual/aula/{numero_de_aula}:
      get:
        summary: Obtener información de un aula por numero de aula
        parameters:
          - name: numero_de_aula
            in: path
            type: integer
            required: true
            description: Número de aula
        responses:
          200:
            description: Respuesta exitosa
            schema:
              $ref: "#/definitions/Aula"
  /visual/profesor/{nombre}:
    get:
      summary: Obtener información de un profesor por ID
      parameters:
        - name: nombre
          in: path
          type: string
          required: true
          description: Nombre del profesor
      responses:
        200:
          description: Respuesta exitosa
          schema:
            $ref: "#/definitions/Profesor"
        404:
          description: Error al introducir el nombre del profesor
          schema:
            $ref: "#/definitions/VisualException"
        500:
          description: Error interno de servidor
          schema:
            $ref: "#/definitions/VisualException"
  /visual/getPortatil/{numeroJuntaAndalucia}:
    get:
      operationId: getPCByNumeroJunta
      description: Se obtiene un ordenador por el numero de la junta
      parameters:
        - name: numeroJuntaAndalucia
          description: Numero de la junta que identifica a un ordenador
          type: string
          in: path
          required: true
      responses:
        200:
          description: Ordenador obtenido
          schema:
            $ref: "#/definitions/Portatil"
        404:
          description: Error al introducir el nombre del profesor
          schema:
            $ref: "#/definitions/VisualException"
        500:
          description: Error al introducir el nombre del profesor
          schema:
            $ref: "#/definitions/VisualException"
  /visual/getPortatil/numSerie/{numeroPlacaBase}:
    get:
      operationId: numeroPlacaBase
      description: obtener el portatil por su placa base
      parameters:
        - name: numeroPlacaBase
          in: path
          description: numero de placa base a obtener
          required: true
          type: integer
          format: int32
      responses:
        200:
          description: Ordenador buscado con exito
        404:
          description: Error al buscar el ordenador
          schema:
            $ref: '#/definitions/VisualException'
        500:
          description: Error de servidor
          schema:
            $ref: '#/definitions/VisualException'
  /visual/getProfesor/{nombre}:
    get:
      operationId: getProfesor
      description: obtener profesor por su id
      parameters:
        - name: nombre
          in: path 
          description: id de profesor a buscar
          required: true
          type: string
      responses:
        200:
          description: Profesor buscado con exito
          schema:
            $ref: '#/definitions/Profesor'
        404:
          description: Error al buscar al profesor
          schema:
            $ref: '#/definitions/VisualException'
        500:
          description: Error de servidor
          schema:
            $ref: '#/definitions/VisualException'
  /visual/getPortatil/pegatina/{number}:
    get:
      operationId: getPortatilByCPU
      description: obtener el portatil por su CPU
      parameters:
        - name: number
          in: path
          description: numero de cpu a obtener
          required: true
          type: integer
          format: int32
      responses:
        200:
          description: Ordenador buscado con exito
          schema: 
            $ref: "#/definitions/Portatil"
        404:
          description: Error al buscar el ordenador
          schema:
            $ref: '#/definitions/VisualException'
        500:
          description: Error de servidor
          schema:
            $ref: '#/definitions/VisualException'
  /visual/getPc/sizeRAM/{size}:
    get:
      operationId: getPcBySizeRAM
      description: Obtains a pc using the RAM size
      parameters:
        - name: size
          type: integer
          format: int32
          description: RAM size to search a PC
          in: path
          required: true
      responses:
        200:
          description: PC returned successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/Portatil"
        404:
          description: Error introducing number cpu
          schema: 
            $ref: "#/definitions/VisualException"
        500:
          description: Internal server error
          schema:
            $ref: "#/definitions/VisualException"
  /visual/getPc/sizeHDD/{sizeHDD}:
    get:
      operationId: getPcBySizeHDD
      description: Obtains a pc using the RAM size
      parameters:
        - name: sizeHDD
          type: integer
          format: int32
          description: Disk size to search in a pc
          in: path
          required: true
      responses:
        200:
          description: PC returned successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/Portatil"
        404:
          description: Error introducing number cpu
          schema: 
            $ref: "#/definitions/VisualException"
        500:
          description: Internal server error
          schema:
            $ref: "#/definitions/VisualException"
  /visual/getLastReboot/{numeroPortatil}:
    get:
      operationId: getLastReboot
      description: Se obtiene el ultimo reinicio de un portatil usando su pegatina
      parameters:
        - name: numeroPortatil
          type: integer
          format: int32
          in: path
          required: true
      responses:
        200:
          description: Ultimo reinicio obtenido satisfactoriamente
          schema:
            $ref: "#/definitions/UltimaAccion"
        404:
          description: Error al introducir parametros
          schema:
            $ref: "#/definitions/VisualException"
        500:
          description: Error interno de servidor
          schema:
            $ref: "#/definitions/VisualException"
  /visual/getLastExe/{numeroPortatil}:
    get:
      operationId: getLastExecutable
      description: Se obtiene el ultimo programa ejecutado de un portatil usando su pegatina
      parameters:
        - name: numeroPortatil
          type: integer
          format: int32
          in: path
          required: true
      responses:
        200:
          description: Ultimo reinicio obtenido satisfactoriamente
          schema:
            $ref: "#/definitions/UltimaAccion"
        404:
          description: Error al introducir parametros
          schema:
            $ref: "#/definitions/VisualException"
        500:
          description: Error interno de servidor
          schema:
            $ref: "#/definitions/VisualException"
  /visual/getLastLink/{numeroPortatil}:
    get:
      operationId: getLastLink
      description: Se obtiene el ultimo enlace de un portatil usando su pegatina
      parameters:
        - name: numeroPortatil
          type: integer
          format: int32
          in: path
          required: true
      responses:
        200:
          description: Ultimo reinicio obtenido satisfactoriamente
          schema:
            $ref: "#/definitions/UltimaAccion"
        404:
          description: Error al introducir parametros
          schema:
            $ref: "#/definitions/VisualException"
        500:
          description: Error interno de servidor
          schema:
            $ref: "#/definitions/VisualException"
  /visual/getLastInstall/{numeroPortatil}:
    get:
      operationId: getLastInstall
      description: Se obtiene la ultima instalacion de un portatil usando su pegatina
      parameters:
        - name: numeroPortatil
          type: integer
          format: int32
          in: path
          required: true
      responses:
        200:
          description: Ultimo reinicio obtenido satisfactoriamente
          schema:
            $ref: "#/definitions/UltimaAccion"
        404:
          description: Error al introducir parametros
          schema:
            $ref: "#/definitions/VisualException"
        500:
          description: Error interno de servidor
          schema:
            $ref: "#/definitions/VisualException"
  /visual/getLastUninstall/{numeroPortatil}:
    get:
      operationId: getLastUninstall
      description: Se obtiene la ultima desinstalacion de un portatil usando su pegatina
      parameters:
        - name: numeroPortatil
          type: integer
          format: int32
          in: path
          required: true
      responses:
        200:
          description: Ultimo reinicio obtenido satisfactoriamente
          schema:
            $ref: "#/definitions/UltimaAccion"
        404:
          description: Error al introducir parametros
          schema:
            $ref: "#/definitions/VisualException"
        500:
          description: Error interno de servidor
          schema:
            $ref: "#/definitions/VisualException"
  /visual/downloadScreenshot/portatil/{numeroPortatil}:
    get:
      operationId: getScreenshotPc
      description: Se obtiene una captura mediante la pegatina de un portatil
      parameters:
        - name: numeroPortatil
          type: integer
          format: int32
          in: path
          required: true
      responses:
        200:
          description: Captura descargada
          schema:
            type: file
        404:
          description: Error al introducir el portatil
          schema:
            $ref: "#/definitions/VisualException"
        500:
          description: Error interno de servidor
          schema:
            $ref: "#/definitions/VisualException"
      produces:
        - multipart/form-data
  /visual/downloadScreenshot/aula/{numero_de_aula}:
    get:
      operationId: getScreenshotAula
      description: Se obtiene una captura mediante un aula
      parameters:
        - name: numero_de_aula
          type: integer
          format: int32
          in: path
          required: true
      responses:
        200:
          description: Captura descargada
          schema:
            type: file
        404:
          description: Error al introducir el portatil
          schema:
            $ref: "#/definitions/VisualException"
        500:
          description: Error interno de servidor
          schema:
            $ref: "#/definitions/VisualException"
      produces:
        - multipart/form-data
  /visual/downloadScreenshot/profesor/{nombre}:
    get:
      operationId: getScreenshotProfesor
      description: Se obtiene una captura mediante un profesor
      parameters:
        - name: nombre
          type: string
          in: path
          required: true
      responses:
        200:
          description: Captura descargada
          schema:
            type: file
        404:
          description: Error al introducir el portatil
          schema:
            $ref: "#/definitions/VisualException"
        500:
          description: Error interno de servidor
          schema:
            $ref: "#/definitions/VisualException"
      produces:
        - multipart/form-data
#OBJETOS
definitions:
  Portatil:
    type: object
    properties: 
      numeroJuntaAndalucia:
        type: integer
        format: int32
        description: "Numero de la junta de andalucia"
      numeroPlacaBase:
        type: integer
        format: int32
        description: "Numero de la placa base del portatil"
      numeroPortatil:
        type: integer
        format: int32
        description: "Pegatina que posee el portatil"
      status:
        type: boolean
        description: true if the pc is on, false if the pc is off
        default: true
      reboot: 
        type: boolean
        default: false
        description: set the pc of if this value is true
      locked:
        type: boolean
        description: lock the pc if this value is true
      appsInstalled:
        type: array
        description: An array of apps that the pc have installed
        items:
          $ref: "#/definitions/App"
      Hardware:
        type: object
        $ref: '#/definitions/Hardware'
  Hardware:
    type: object
    properties: 
        CPU:
          $ref: '#/definitions/CPU'
        RAM:
          $ref: '#/definitions/RAM'
        HardDisk:
          $ref: '#/definitions/HardDisk'
  CPU:
    properties:
      number:
        type: integer
        format: int32
      brand:
        type: string
  RAM:
    properties: 
      size: 
        type: integer
        format: int32
      brand: 
        type: string
  HardDisk:
    properties: 
      size: 
        type: integer
        format: int32
      currentSize: 
        type: integer
        format: int32
      brand: 
        type: string
  App:
    type: object
    properties: 
      nameApp:
        type: string
      isMalware:
        type: boolean
        default: false
      uninstall:
        type: boolean
        default: false
      execute:
        type: boolean
        default: false
  Profesor:
    type: object
    properties:
      id:
        type: integer
        format: int64
      nombre:
        type: string
  Aula:
    type: object
    properties:
      numero_de_aula:
        type: integer
        description: Número de aula
      id_profesor:
        type: integer
        description: Identificador del profesor asignado
  VisualException:
    type: object
    properties: 
      errorCode:
        type: integer
        format: int32
      description:
        type: string
      errorSeverity:
        type: string
  UltimaAccion:
    type: object
    properties: 
      ultimoReinicio:
        type: string
        description: Ultimo reinicio realizado en tipo date almacenado en string
      ultimaEjecucion:
        type: string
        description: Ultima ejecucion realizada en tipo date almacenado en string
      ultimoBloqueo:
        type: string
        description: Ultimo bloqueo realizado en tipo date almacenado en string
      ultimoEnlace:
        type: string
        description: Ultimo enlace abierto realizado en tipo date almacenado en string
      ultimaInstalacion:
        type: string
        description: Ultima app instalada abierta realizado en tipo date almacenado en string
      ultimaDesinstalacion:
        type: string
        description: Ultima app desinstalada abierta realizado en tipo date almacenado en string