#Autor Adrian Verdejo
#TODO Realizar un put en el que se actualiza un portatil usando el numero de la junta como parametro
swagger: '2.0'
schemes:
  - "https"
info:
  title: Actualizacion de PC pro junta de andalucia file 9
  version: 1.0.0
  contact:
     name: "Adrian Verdejo"
     email: "avergar952@g.educaand.es"
#TODO El path que tienes que usar es /admin/updatePC/{numeroJuntaAndalucia}


#OBJETOS
definitions:
  Portatil:
    type: object
    properties: 
      numeroJuntaAndalucia:
        type: integer
        format: int32
        description: "Numero de la junta de andalucia"
      numeroPlacaBase:
        type: integer
        format: int32
        description: "Numero de la placa base del portatil"
      numeroPortatil:
        type: integer
        format: int32
        description: "Pegatina que posee el portatil"
      status:
        type: boolean
        description: true if the pc is on, false if the pc is off
        default: true
      reboot: 
        type: boolean
        default: false
        description: set the pc of if this value is true
      locked:
        type: boolean
        description: lock the pc if this value is true
      appsInstalled:
        type: array
        description: An array of apps that the pc have installed
        $ref: "#definitions/App"
      Hardware:
        $ref: '#definitions/Hardware'
  Hardware:
    type: object
    properties: 
        CPU:
          $ref: '#/definitions/CPU'
        RAM:
          $ref: '#/definitions/RAM'
        HardDisk:
          $ref: '#/definitions/HardDisk'
  CPU:
    properties:
      number:
        type: integer
        format: int32
      brand:
        type: string
  RAM:
    properties: 
      size: 
        type: integer
        format: int32
      brand: 
        type: string
  HardDisk:
    properties: 
      size: 
        type: integer
        format: int32
      currentSize: 
        type: integer
        format: int32
      brand: 
        type: string
  App:
    type: object
    properties: 
      nameApp:
        type: string
      isMalware:
        type: boolean
        default: false
      uninstall:
        type: boolean
        default: false
      execute:
        type: boolean
        default: false
  AdminException:
    type: object
    properties: 
      errorCode:
        type: integer
        format: int32
      description:
        type: string
      errorSeverity:
        type: string