#Autor Pablo Ruiz Canovas
swagger: '2.0'
host: reaktor
basePath: /reaktor
schemes:
  - https
info: 
  version: 1.0.0
  title: Admin especification file 1
  description: Turn off and reboot the pc
  contact:
    name: Pablo Ruiz Canovas
    email: pruican1312@g.educaand.es
paths: 
  /admin/turnOf/{status}:
    get:
      operationId: turnOffPc
      description: Turn off the pc using the status param
      parameters:
        - name: status 
          type: boolean
          description: True if teh pc is on or false if the pc is off
          in: path
          required: true
      responses:
        200:
          description: PC turn off successfully
          schema: 
            $ref: "#definitions/Portatil"
        404:
          description: "Error trying set off the pc"
          schema:
            $ref: "#/definitions/AdminException"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/AdminException"

      produces:
        - application/json
  
  /admin/reboot/{reboot}:
    get:
      operationId: rebootPc
      description: Reboot the pc using the reboot param
      parameters:
        - name: reboot 
          type: boolean
          description: True if the pc will be rebooted or false if not
          in: path
          required: true
      responses:
        200:
          description: PC turn off successfully
          schema: 
            $ref: "#definitions/Portatil"
        404:
          description: "Error trying reboot the pc"
          schema:
            $ref: "#/definitions/AdminException"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/AdminException"
      produces:
        - application/json


definitions:
  Portatil:
    type: object
    properties: 
      numeroJuntaAndalucia:
        type: integer
        format: int32
        description: "Numero de la junta de andalucia"
      numeroPlacaBase:
        type: integer
        format: int32
        description: "Numero de la placa base del portatil"
      numeroPortatil:
        type: integer
        format: int32
        description: "Pegatina que posee el portatil"
      status:
        type: boolean
        description: true if the pc is on, false if the pc is off
        default: true
      reboot: 
        type: boolean
        default: false
        description: set the pc of if this value is true
      Hardware:
        $ref: '#definitions/Hardware'
  Hardware:
    type: object
    properties: 
        CPU:
          $ref: '#/definitions/CPU'
        RAM:
          $ref: '#/definitions/RAM'
        HardDisk:
          $ref: '#/definitions/HardDisk'
  CPU:
    properties:
      number:
        type: integer
        format: int32
      brand:
        type: string
  RAM:
    properties: 
      size: 
        type: integer
        format: int32
      brand: 
        type: string
  HardDisk:
    properties: 
      size: 
        type: integer
        format: int32
      currentSize: 
        type: integer
        format: int32
      brand: 
        type: string
  AdminException:
    type: object
    properties: 
      errorCode:
        type: integer
        format: int32
      description:
        type: string
      errorSeverity:
        type: string
