#Autor Eduardo Moreno
#TODO Crear un put que pida como parametro en el path "lock" que devuelva un application/json referenciando al objeto portatil
swagger: '2.0'
host: reaktor
basePath: /reaktor
schemes:
  - https
info: 
  version: 1.0.0
  title: Admin especification file 3
  description: Send a screenshot file
  contact:
    name:  Eduardo Moreno
    email: emoralg196@g.educaand.es
#TODO Establecer el path /admin/lockPC/{lock} con los requisitos mencionados
paths:
  /admin/portatiles/{lock}:
    put:
      summary: Actualizar un port치til por su identificador de bloqueo
      parameters:
        - name: lock
          in: path
          description: Identificador de bloqueo del port치til
          required: true
          type: string
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: Operaci칩n exitosa
          schema:
            $ref: "#/definitions/Portatil"
        404:
          description: Port치til no encontrado
        500:
          description: Error interno del servidor
#OBJETOS
definitions:
  Portatil:
    type: object
    properties: 
      numeroJuntaAndalucia:
        type: integer
        format: int32
        description: "Numero de la junta de andalucia"
      numeroPlacaBase:
        type: integer
        format: int32
        description: "Numero de la placa base del portatil"
      numeroPortatil:
        type: integer
        format: int32
        description: "Pegatina que posee el portatil"
      status:
        type: boolean
        description: true if the pc is on, false if the pc is off
        default: true
      reboot: 
        type: boolean
        default: false
        description: set the pc of if this value is true
      locked:
        type: boolean
        description: lock the pc if this value is true
      appsInstalled:
        type: array
        description: An array of apps that the pc have installed
        $ref: "#definitions/App"
      Hardware:
        $ref: '#definitions/Hardware'
  Hardware:
    type: object
    properties: 
        CPU:
          $ref: '#/definitions/CPU'
        RAM:
          $ref: '#/definitions/RAM'
        HardDisk:
          $ref: '#/definitions/HardDisk'
  CPU:
    properties:
      number:
        type: integer
        format: int32
      brand:
        type: string
  RAM:
    properties: 
      size: 
        type: integer
        format: int32
      brand: 
        type: string
  HardDisk:
    properties: 
      size: 
        type: integer
        format: int32
      currentSize: 
        type: integer
        format: int32
      brand: 
        type: string
  App:
    type: object
    properties: 
      nameApp:
        type: string
      isMalware:
        type: boolean
        default: false
      uninstall:
        type: boolean
        default: false
      execute:
        type: boolean
        default: false