#Autor Eduardo Moreno
#TODO Enviar ficheros simulando que son capturas mediante post, no hace falta el uso de objetos
swagger: '2.0'
host: reaktor
basePath: /reaktor
schemes:
  - https
info: 
  version: 1.0.0
  title: Admin especification file 4
  description: Send a screenshot file
  contact:
    name:  Eduardo Moreno, Adrian Verdejo
    email: emoralg196@g.educaand.es
#TODO Establecer el path /admin/uploadScreenshot con los requisitos mencionados
paths:
  /admin/uploadScreenshot:
    post:
      summary: Cargar captura de pantalla
      description: Enviar una captura de pantalla simulada.
      consumes:
        - multipart/form-data
      parameters:
        - name: screenshot
          in: formData
          description: Archivo de captura de pantalla
          required: true
          type: file
      responses:
        200:
          description: Archivo cargado con éxito
        400:
          description: Solicitud incorrecta
        500:
          description: Error del servidor
  /admin/downloadScreenshot:
    get:
      operationId: downloadScreenshot
      description: Descarga de una captura de pantalla
      responses:
        200:
          description: Captura descargada con exito
          schema:
            type: file
        500:
          description: Error de servidor
          schema:
            $ref: "#/definitions/AdminException"
      produces:
        - multipart/form-data
