#Autor Adrian Verdejo
swagger: '2.0'
info:
  version: 1.0.0
  title: Objeto carrito
schemes:
 - http
paths:
  /carrito:
    get:
      operationId: getCarrito
      description: Obtener el objeto carrito
      responses:
        200:
          description: Todo a salido correctamente
          schema:
            $ref: '#/definitions/Carrito'
        400:
          description: Error
definitions:
   Carrito:
    type: object
    properties: 
      identifier:
        type: integer
        description: Identificador del carrito
      ordenadores:
        type: array
        description: Array de ordenadores