#Autor Pablo Ruiz Canovas
swagger: '2.0'
info:
  title: "Diseño del objeto portatil"
  version: 1.0.0 
schemes:
  - http
produces:
  - json
paths:
  /portatil:
    get:
      operationId: getPortatil
      description: "Devuelve un objeto portatil"
      responses:
        200:
          description: "La respuesta es un objeto portatil"
          schema:
            $ref: "#/definitions/Portatil"
        400:
          description: "Error al delvolver el objeto portatil"
definitions:
  Portatil:
    type: object
    properties: 
      numeroJuntaAndalucia:
        type: integer
        format: int32
        description: "Numero de la junta de andalucia"
      numeroPlacaBase:
        type: integer
        format: int32
        description: "Numero de la placa base del portatil"
      numeroPortatil:
        type: integer
        format: int32
        description: "Pegatina que posee el portatil"
      status:
        type: boolean
        description: true if the pc is on, false if the pc is off
        default: true
      reboot: 
        type: boolean
        default: false
        description: set the pc of if this value is true
      locked:
        type: boolean
        description: lock the pc if this value is true
      appsInstalled:
        type: array
        description: An array of apps that the pc have installed
        $ref: "#definitions/App"
      Hardware:
        $ref: '#definitions/Hardware'
  Hardware:
    type: object
    properties: 
        CPU:
          $ref: '#/definitions/CPU'
        RAM:
          $ref: '#/definitions/RAM'
        HardDisk:
          $ref: '#/definitions/HardDisk'
  CPU:
    properties:
      number:
        type: integer
        format: int32
      brand:
        type: string
  RAM:
    properties: 
      size: 
        type: integer
        format: int32
      brand: 
        type: string
  HardDisk:
    properties: 
      size: 
        type: integer
        format: int32
      currentSize: 
        type: integer
        format: int32
      brand: 
        type: string
  App:
    type: object
    properties: 
      appType:
        type: string
      isMalware:
        type: boolean
        default: false
      uninstall:
        type: boolean
        default: false
      execute:
        type: boolean
        default: false




  



