swagger: '2.0'
info:
  version: 1.0.0
  title: API de Profesores
paths:
  /profesores:
    get:
      summary: Obtiene la lista de profesores
      responses:
        '200':
          description: Lista de profesores
definitions:
  Profesor:
    type: object
    properties:
      id:
        type: integer
        format: int64
      nombre:
        type: string
